# ========================= inference_v15.py ===========================
"""
Minimal inference for defect_overlay_unet_v15

Inputs (only):
  --good_dir   : folder of true-good images (recursively scanned)
  --gen_ckpt   : path to trained G .pt (from v15 training)

Output (only):
  outputs/fake_defect_v15/  (flat directory, one image per input)

Each output is a 1024px synthetic defect composed as: synth = bg + overlay,
where bg is the normalized/centered 256px background upsampled to 1024px and
overlay is generated by G from [bg, tiled-noise].
"""
# ----------------------------------------------------------------------
import argparse, os
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as T
import torchvision.utils as vutils
from PIL import Image
from tqdm import tqdm

# ----------------------- constants to match training ------------------
RES_TRAIN = 256
RES_FULL  = 1024
NZ_TILE   = 8  # 8x8 tiled noise used in training
ALLOWED   = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}
OUT_DIR   = Path("outputs/fake_defect_v15")

torch.set_num_threads(max(os.cpu_count() - 1, 1))

# ----------------------------- utils ---------------------------------
def is_img(p: Path) -> bool:
    return p.is_file() and p.suffix.lower() in ALLOWED

def denorm01(x: torch.Tensor) -> torch.Tensor:
    # [-1,1] -> [0,1]
    return (x.clamp(-1, 1) * 0.5) + 0.5

def save_tensor_img(x: torch.Tensor, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    vutils.save_image(denorm01(x), str(path))

# ----------------------- transforms (match train) ---------------------
class PadSquare:
    def __init__(self, s): self.s = s
    def __call__(self, img: Image.Image):
        w, h = img.size
        side = max(w, h, self.s)
        pad_l = (side - w) // 2
        pad_t = (side - h) // 2
        pad = [pad_l, pad_t, side - w - pad_l, side - h - pad_t]
        return T.functional.pad(img, pad, padding_mode='reflect')

xform = T.Compose([
    T.Grayscale(),
    PadSquare(RES_TRAIN),
    T.Resize((RES_TRAIN, RES_TRAIN), interpolation=T.InterpolationMode.BILINEAR),
    T.ToTensor(),
    T.Normalize((0.5,), (0.5,))
])

# ----------------------------- model G --------------------------------
def sn(l): return nn.utils.spectral_norm(l)

class Up(nn.Module):
    def __init__(self, i, o):
        super().__init__()
        self.up = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv = sn(nn.Conv2d(i, o, 3, 1, 1, bias=False))
        self.bn = nn.BatchNorm2d(o)
        self.act = nn.ReLU(True)
    def forward(self, x): return self.act(self.bn(self.conv(self.up(x))))

class G(nn.Module):
    # UNet (resize-conv), input channels: 1(bg)+1(noise)=2, clamp ±0.5
    def __init__(self, ch=64, in_ch=2):
        super().__init__()
        self.e1 = nn.Sequential(sn(nn.Conv2d(in_ch, ch, 4, 2, 1, bias=False)),
                                nn.LeakyReLU(0.2, True))
        self.e2 = nn.Sequential(sn(nn.Conv2d(ch, ch*2, 4, 2, 1, bias=False)),
                                nn.BatchNorm2d(ch*2), nn.LeakyReLU(0.2, True))
        self.e3 = nn.Sequential(sn(nn.Conv2d(ch*2, ch*4, 4, 2, 1, bias=False)),
                                nn.BatchNorm2d(ch*4), nn.LeakyReLU(0.2, True))
        self.e4 = nn.Sequential(sn(nn.Conv2d(ch*4, ch*8, 4, 2, 1, bias=False)),
                                nn.BatchNorm2d(ch*8), nn.LeakyReLU(0.2, True))
        self.e5 = nn.Sequential(sn(nn.Conv2d(ch*8, ch*8, 4, 2, 1, bias=False)),
                                nn.BatchNorm2d(ch*8), nn.LeakyReLU(0.2, True))
        self.d5 = Up(ch*8,  ch*8)
        self.d4 = Up(ch*16, ch*4)
        self.d3 = Up(ch*8,  ch*2)
        self.d2 = Up(ch*4,  ch)
        self.out = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='nearest'),
            sn(nn.Conv2d(ch*2, 1, 3, 1, 1, bias=False))
        )
    def forward(self, x):
        e1 = self.e1(x); e2 = self.e2(e1); e3 = self.e3(e2); e4 = self.e4(e3)
        e5 = self.e5(e4)
        d5 = self.d5(e5)
        d4 = self.d4(torch.cat([d5, e4], 1))
        d3 = self.d3(torch.cat([d4, e3], 1))
        d2 = self.d2(torch.cat([d3, e2], 1))
        out = self.out(torch.cat([d2, e1], 1))
        return torch.clamp(out, -0.5, 0.5)  # overlay @ 256px

# ------------------------------- main --------------------------------
@torch.inference_mode()
def main():
    ap = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument("--good_dir", required=True, type=Path, help="Folder of true good images (recursively scanned)")
    ap.add_argument("--gen_ckpt", required=True, type=Path, help="Path to trained G .pt (v15)")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Load generator
    netG = G().to(device).eval()
    netG.load_state_dict(torch.load(args.gen_ckpt, map_location=device))

    # Collect inputs
    good_paths = [p for p in args.good_dir.rglob("*") if is_img(p)]
    if not good_paths:
        raise SystemExit(f"No images found in {args.good_dir}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Generate one output per input (flat output dir)
    counter = 0
    for ipath in tqdm(good_paths, desc="Generating", unit="img"):
        # 1) preprocess background to 256
        img = Image.open(ipath).convert("L")
        bg = xform(img).unsqueeze(0).to(device)           # [1,1,256,256]

        # 2) tiled noise -> 256
        z = torch.randn(1, 1, NZ_TILE, NZ_TILE, device=device)
        z = F.interpolate(z, (RES_TRAIN, RES_TRAIN), mode="nearest")

        # 3) overlay @256 and compose @1024
        ov   = netG(torch.cat([bg, z], 1))                # [-0.5,0.5]
        bgF  = F.interpolate(bg, (RES_FULL, RES_FULL), mode="bilinear", align_corners=False)
        ovF  = F.interpolate(ov, (RES_FULL, RES_FULL), mode="bilinear", align_corners=False)
        synthF = torch.clamp(bgF + ovF, -1, 1)            # final synthetic defect

        # 4) save with collision-safe flat naming
        counter += 1
        stem = ipath.stem
        out_name = f"{counter:06d}_{stem}_synth.png"
        save_tensor_img(synthF, OUT_DIR / out_name)

    print(f"✅ Wrote {counter} images to {OUT_DIR.resolve()}")

if __name__ == "__main__":
    main()
# ======================================================================
